version: '3.8'

services:
  app:
    image: 'ecommerce-product-module:latest'
    build:
      context: .
    container_name: ecommerce-product-module
    depends_on:
      - db
    ports:
      - "6868:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://ecommerce-product-postgresql:5432/ecommerce-product-db
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
  db:
    container_name: ecommerce-product-postgresql
    image: 'postgres:latest'
    environment:
      - POSTGRES_DB=ecommerce-product-db
      - POSTGRES_PASSWORD=root
      - POSTGRES_USER=postgres
    ports:
      - '1453:5432'
    expose:
      - '1453'
